name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt list
      run: sudo apt update
    - name: Set up compiler
      run: sudo apt install gcc-cross-x86_64-elf 
    - name: Make kernel
      run: make build-x86_64
