name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt list
      run: sudo apt update
    - name: Set up x86_64-elf-gcc toolchain
      run: | 
        git clone https://github.com/lordmilko/i686-elf-tools
        cd i686-elf-tools
        chmod +x i686-elf-tools.sh
        sudo ./i686-elf-tools.sh
    - name: Make kernel
      run: make build-x86_64
