name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt list
      run: sudo apt update
    - name: Set up QEMU Arm toolchain
      run: |
        wget -O toolchain.tar.gz <URL_TO_YOUR_TOOLCHAIN>
        tar -xzf toolchain.tar.gz
        export PATH="$PWD/xpack-qemu-arm/bin:$PATH"
    - name: Install dependencies
      run: sudo apt install grub2-common grub-pc g++ gcc build-essential
    - name: Make kernel
      run: make build-x86_64
