name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt list
      run: sudo apt update && apt upgrade
    - name: Install dependencies
      run: sudo apt install grub2-common grub-pc g++ gcc build-essential
    - name: Make kernel
      run: make build-x86_64
