name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt list
      run: sudo apt update
    - name: Set up x86_64-elf-gcc toolchain
      run: | 
        git clone https://github.com/danidoco/x86_64-elf-gcc/
        cd x86_64-elf-gcc
        chmod +x setup.sh
        sudo ./setup.sh
    - name: Make kernel
      run: make build-x86_64
