name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install necessary dependencies for the toolchain build
    - name: Install build and make dependencies
      run: |
        sudo apt update
        sudo apt install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo nasm -y

    # Download and install the standard x86_64-elf GCC toolchain
    - name: Download and install x86_64-elf GCC toolchain
      run: |
        export PREFIX="/usr/local/x86_64elfgcc"
        export TARGET=x86_64-elf
        export PATH="$PREFIX/bin:$PATH"

        mkdir -p /tmp/src
        cd /tmp/src

        # Download and build binutils (including ld)
        curl -O http://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.gz
        tar xf binutils-2.37.tar.gz
        mkdir binutils-build
        cd binutils-build
        ../binutils-2.37/configure --target=$TARGET --prefix=$PREFIX --with-sysroot --disable-nls --disable-werror
        make -j$(nproc)
        sudo make install

        # Download and build GCC
        cd /tmp/src
        curl -O https://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.gz
        tar xf gcc-11.2.0.tar.gz
        mkdir gcc-build
        cd gcc-build
        ../gcc-11.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++
        make all-gcc -j$(nproc)
        make all-target-libgcc -j$(nproc)
        sudo make install-gcc
        sudo make install-target-libgcc

    # Build the x86_64-elf kernel
    - name: Build x86_64-elf kernel
      run: sudo make build-x86_64
